# Generated by Django 5.2.17 on 2026-09-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='TrueTechs', max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='e.g. IT · AUTOMATION · BPO', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='header/')),
                ('cta_text', models.CharField(blank=True, help_text='e.g. Get a quote', max_length=50)),
                ('cta_link', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Header & Navigation',
                'verbose_name_plural': 'Header & Navigation',
            },
        ),
        migrations.CreateModel(
            name='NavMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('link', models.CharField(help_text='URL or path, e.g. /services or #services', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='core.siteheader')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
