# Generated by Django 5.2.17 on 2026-09-21 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. IT INFRASTRUCTURE SUPPORT', max_length=100)),
                ('heading_main', models.CharField(help_text='e.g. Keep your systems running', max_length=150)),
                ('heading_highlight', models.CharField(blank=True, help_text='Accent-coloured second line, e.g. day and night.', max_length=150)),
                ('subtext', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('primary_cta_text', models.CharField(blank=True, help_text='e.g. Get a quote', max_length=50)),
                ('primary_cta_link', models.CharField(blank=True, max_length=255)),
                ('secondary_cta_text', models.CharField(blank=True, help_text='e.g. View services', max_length=50)),
                ('secondary_cta_link', models.CharField(blank=True, max_length=255)),
                ('stat_value', models.CharField(blank=True, help_text='e.g. 99.97%', max_length=20)),
                ('stat_caption', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='HeroFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name, e.g. bolt, cloud, backup, desktop_windows', max_length=50)),
                ('label', models.CharField(help_text='e.g. 24/7 NOC', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.herosection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
