# Generated by Django 5.2.17 on 2026-09-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_herosection_herofeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. AI & AUTOMATION', max_length=100)),
                ('heading_main', models.CharField(help_text='e.g. Put the repetitive work on', max_length=150)),
                ('heading_highlight', models.CharField(blank=True, help_text='Accent-coloured second line, e.g. autopilot.', max_length=150)),
                ('subtext', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=5)),
                ('image_badge_text', models.CharField(blank=True, help_text='Floating badge on the image, e.g. Live automation running', max_length=100)),
                ('image_tags', models.CharField(blank=True, help_text='Comma-separated short tags shown in the badge, e.g. AI, RPA, DOC, CRM', max_length=150)),
                ('corner_badge_icon', models.CharField(blank=True, help_text='Material icon name for the bottom-left floating badge', max_length=50)),
                ('corner_badge_title', models.CharField(blank=True, help_text='e.g. Workflows automated', max_length=100)),
                ('corner_badge_subtitle', models.CharField(blank=True, help_text='e.g. Across 4 service lines', max_length=150)),
                ('cta_heading', models.CharField(blank=True, help_text='e.g. Ready to automate?', max_length=150)),
                ('cta_subtext', models.CharField(blank=True, help_text='e.g. We build around your existing systems.', max_length=200)),
                ('cta_button_text', models.CharField(blank=True, help_text='e.g. Get started', max_length=50)),
                ('cta_button_link', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name, e.g. smart_toy, sync, description, sync_alt', max_length=50)),
                ('title', models.CharField(help_text='e.g. AI chatbots', max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.serviceshowcase')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
