# Generated by Django 5.2.17 on 2026-09-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_serviceshowcase_servicefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceshowcase',
            name='bottom_tags',
            field=models.CharField(blank=True, help_text='Comma-separated pills below the features, e.g. Voice, Email, Chat, WhatsApp, 24/7', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceshowcase',
            name='image_stat_caption',
            field=models.CharField(blank=True, help_text='e.g. Support coverage', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceshowcase',
            name='image_stat_value',
            field=models.CharField(blank=True, help_text='Stat-style badge on the image, e.g. 24/7', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceshowcase',
            name='corner_badge_icon',
            field=models.CharField(blank=True, help_text='Material icon name for the floating corner badge', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceshowcase',
            name='corner_badge_subtitle',
            field=models.CharField(blank=True, help_text='e.g. Across 4 service lines / Voice · Chat · Email', max_length=150),
        ),
        migrations.AlterField(
            model_name='serviceshowcase',
            name='corner_badge_title',
            field=models.CharField(blank=True, help_text='e.g. Workflows automated / ACTIVE CHANNELS', max_length=100),
        ),
    ]
