# Generated by Django 5.2.17 on 2026-09-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_serviceshowcase_bottom_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. WHO WE ARE', max_length=100)),
                ('heading', models.CharField(help_text='e.g. Two offices, one team, and the work that never stops.', max_length=255)),
                ('body_text', models.TextField(blank=True, help_text='Paragraphs separated by a blank line')),
                ('office1_image', models.ImageField(blank=True, null=True, upload_to='offices/')),
                ('office1_badge_label', models.CharField(blank=True, help_text='e.g. HEAD OFFICE', max_length=50)),
                ('office1_city', models.CharField(blank=True, help_text='e.g. Dubai, UAE', max_length=100)),
                ('office1_subcaption', models.CharField(blank=True, help_text='e.g. Commercial relationship · GST UTC+4', max_length=150)),
                ('office1_pill_label', models.CharField(blank=True, help_text='e.g. DUBAI', max_length=30)),
                ('office2_image', models.ImageField(blank=True, null=True, upload_to='offices/')),
                ('office2_badge_label', models.CharField(blank=True, help_text='e.g. DELIVERY CENTRE', max_length=50)),
                ('office2_city', models.CharField(blank=True, help_text='e.g. Chennai, India', max_length=100)),
                ('office2_subcaption', models.CharField(blank=True, help_text='e.g. Technical delivery · IST UTC+5:30', max_length=150)),
                ('office2_pill_label', models.CharField(blank=True, help_text='e.g. CHENNAI', max_length=30)),
            ],
            options={
                'verbose_name': 'Who We Are',
                'verbose_name_plural': 'Who We Are',
            },
        ),
    ]
