# Generated by Django 5.2.17 on 2026-09-21 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_whowearesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. WHY WORK WITH US', max_length=100)),
                ('heading', models.CharField(help_text='e.g. Support measured by what it changes in your operation.', max_length=255)),
                ('subtext', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='why/')),
                ('image_badge_label', models.CharField(blank=True, help_text='e.g. One partner', max_length=100)),
                ('image_badge_value', models.CharField(blank=True, help_text='e.g. 8 service lines', max_length=100)),
            ],
            options={
                'verbose_name': 'Why Work With Us',
                'verbose_name_plural': 'Why Work With Us',
            },
        ),
        migrations.CreateModel(
            name='WhyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name, e.g. verified_user, bolt, trending_up', max_length=50)),
                ('title', models.CharField(help_text='e.g. Reliable expertise', max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Alternates left/right around the image in display order')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.whysection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
