# Generated by Django 5.2.17 on 2026-09-21 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_whysection_whyfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. HOW WE WORK', max_length=100)),
                ('heading', models.CharField(help_text='e.g. Three commitments we hold to on every engagement.', max_length=255)),
            ],
            options={
                'verbose_name': 'How We Work',
                'verbose_name_plural': 'How We Work',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='process/')),
                ('title', models.CharField(help_text='e.g. Scoped, not templated', max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Also sets the displayed step number (01, 02, ...)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.processsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
