# Generated by Django 5.2.17 on 2026-09-21 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_processsection_processstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeDoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. WHAT WE DO', max_length=100)),
                ('heading', models.CharField(help_text='e.g. Eight service lines, one point of contact.', max_length=255)),
                ('subtext', models.CharField(blank=True, help_text='e.g. Take a single line, or run several under one agreement with the same team behind them.', max_length=255)),
            ],
            options={
                'verbose_name': 'What We Do',
                'verbose_name_plural': 'What We Do',
            },
        ),
        migrations.CreateModel(
            name='WhatWeDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name, e.g. hub, security, smart_toy', max_length=50)),
                ('title', models.CharField(help_text='e.g. 24/7 IT Infrastructure Support', max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='what-we-do/')),
                ('bullet_points', models.TextField(blank=True, help_text='One bullet per line, e.g. 24/7 NOC and service desk')),
                ('cta_text', models.CharField(blank=True, default='Enquire About This Service', max_length=50)),
                ('cta_link', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Also sets the displayed number (01, 02, ...)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.whatwedosection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
