# Generated by Django 5.2.17 on 2026-09-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_whatwedosection_whatwedoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. WHERE WE WORK FROM', max_length=100)),
                ('heading', models.CharField(help_text='e.g. Dubai for the relationship, Chennai for the engineering.', max_length=255)),
                ('subtext', models.TextField(blank=True)),
                ('office1_image', models.ImageField(blank=True, null=True, upload_to='offices/')),
                ('office1_badge_label', models.CharField(blank=True, help_text='e.g. HEAD OFFICE', max_length=50)),
                ('office1_city', models.CharField(blank=True, help_text='e.g. Dubai, UAE', max_length=100)),
                ('office1_address', models.CharField(blank=True, max_length=255)),
                ('office1_timezone', models.CharField(blank=True, help_text='e.g. GST · UTC+4', max_length=50)),
                ('office1_phone', models.CharField(blank=True, max_length=30)),
                ('office2_image', models.ImageField(blank=True, null=True, upload_to='offices/')),
                ('office2_badge_label', models.CharField(blank=True, help_text='e.g. DELIVERY CENTRE', max_length=50)),
                ('office2_city', models.CharField(blank=True, help_text='e.g. Chennai, India', max_length=100)),
                ('office2_address', models.CharField(blank=True, max_length=255)),
                ('office2_timezone', models.CharField(blank=True, help_text='e.g. IST · UTC+5:30', max_length=50)),
                ('office2_phone', models.CharField(blank=True, max_length=30)),
                ('banner_icon1', models.CharField(blank=True, help_text='Material icon name, e.g. schedule', max_length=50)),
                ('banner_title1', models.CharField(blank=True, help_text='e.g. Around the clock', max_length=100)),
                ('banner_text1', models.CharField(blank=True, max_length=255)),
                ('banner_icon2', models.CharField(blank=True, help_text='Material icon name, e.g. public', max_length=50)),
                ('banner_title2', models.CharField(blank=True, help_text='e.g. Channels', max_length=100)),
                ('banner_tags2', models.CharField(blank=True, help_text='Comma-separated, e.g. Voice, Chat, Email', max_length=150)),
            ],
            options={
                'verbose_name': 'Offices',
                'verbose_name_plural': 'Offices',
            },
        ),
    ]
