# Generated by Django 5.2.17 on 2026-09-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_officessection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. QUESTIONS', max_length=100)),
                ('heading', models.CharField(help_text='e.g. What clients ask before they start.', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faq/')),
                ('quote_text', models.TextField(blank=True, help_text='e.g. One point of contact for your core operational needs, with consistent quality and measurable results.')),
                ('quote_attribution', models.CharField(blank=True, help_text='e.g. TrueTechs', max_length=100)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.faqsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
