# Generated by Django 5.2.17 on 2026-09-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_faqsection_faqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. GET IN TOUCH', max_length=100)),
                ('heading', models.CharField(help_text='e.g. Tell us what your operation needs.', max_length=255)),
                ('subtext', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('submit_button_text', models.CharField(blank=True, default='Send Your Enquiry', max_length=50)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('service_interested', models.CharField(blank=True, max_length=150)),
                ('requirement', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='e.g. One point of contact across all service lines', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.contactsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
