# Generated by Django 5.2.17 on 2026-09-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactsection_contactsubmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='e.g. IT infrastructure, automation and business process operations — delivered from Dubai and Chennai.')),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('contact_email', models.CharField(blank=True, help_text="e.g. hello@truetechs.com, or 'To be confirmed'", max_length=150)),
                ('hours_text', models.CharField(blank=True, help_text='e.g. Service desk 24/7 · Office hours GST and IST', max_length=150)),
                ('copyright_text', models.CharField(blank=True, help_text='e.g. © 2026 TrueTechs. All rights reserved.', max_length=150)),
                ('bottom_note', models.CharField(blank=True, help_text='e.g. 24/7 monitoring and service desk', max_length=150)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_label', models.CharField(help_text='Column this link appears under, e.g. Quick Links, Services', max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('link', models.CharField(help_text='URL or path', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footersection')),
            ],
            options={
                'ordering': ['group_label', 'order'],
            },
        ),
    ]
