# Generated by Django 5.2.17 on 2026-09-21 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_footersection_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProcessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. OUR PROCESS', max_length=100)),
                ('heading', models.CharField(help_text='e.g. From first assessment to steady state.', max_length=255)),
                ('subtext', models.CharField(blank=True, help_text='e.g. The same six steps whether we take one service line or several.', max_length=255)),
            ],
            options={
                'verbose_name': 'Our Process',
                'verbose_name_plural': 'Our Process',
            },
        ),
        migrations.AddField(
            model_name='whowearesection',
            name='stat1_label',
            field=models.CharField(blank=True, help_text='e.g. Monitoring & service desk', max_length=100),
        ),
        migrations.AddField(
            model_name='whowearesection',
            name='stat1_value',
            field=models.CharField(blank=True, help_text='e.g. 24/7', max_length=20),
        ),
        migrations.AddField(
            model_name='whowearesection',
            name='stat2_label',
            field=models.CharField(blank=True, help_text='e.g. Offices, one team', max_length=100),
        ),
        migrations.AddField(
            model_name='whowearesection',
            name='stat2_value',
            field=models.CharField(blank=True, help_text='e.g. 2', max_length=20),
        ),
        migrations.AddField(
            model_name='whowearesection',
            name='stat3_label',
            field=models.CharField(blank=True, help_text='e.g. Service lines', max_length=100),
        ),
        migrations.AddField(
            model_name='whowearesection',
            name='stat3_value',
            field=models.CharField(blank=True, help_text='e.g. 8', max_length=20),
        ),
        migrations.CreateModel(
            name='OurProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Assess', max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Also sets the displayed step number (01, 02, ...)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.ourprocesssection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
