# Generated by Django 5.2.17 on 2026-09-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ourprocesssection_whowearesection_stat1_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersection',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='footersection',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='footersection',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='footersection',
            name='phone_number',
            field=models.CharField(blank=True, help_text='e.g. +971 50 123 4567 (used for the call icon)', max_length=30),
        ),
        migrations.AddField(
            model_name='footersection',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='footersection',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Digits only with country code, e.g. 971501234567 (used for WhatsApp links)', max_length=20),
        ),
    ]
