# Generated by Django 5.2.17 on 2026-09-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_footersection_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstep',
            name='image',
        ),
    ]
