# Generated by Django 5.2.17 on 2026-09-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_processstep_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='process/'),
        ),
    ]
