# Generated by Django 5.2.17 on 2026-09-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_processstep_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourprocessstep',
            name='icon',
            field=models.CharField(blank=True, help_text='Material icon name, e.g. adjust, share, link, account_tree, headset_mic, auto_awesome', max_length=50),
        ),
    ]
