# Generated by Django 5.2.17 on 2026-09-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ourprocessstep_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersection',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Digits only with country code (e.g. 971501234567) for WhatsApp links, or paste a full URL to link elsewhere instead', max_length=255),
        ),
    ]
