# Generated by Django 5.2.17 on 2026-09-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_footersection_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
    ]
