# Generated by Django 5.2.17 on 2026-09-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_footersection_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='officessection',
            name='banner_badge1',
            field=models.CharField(blank=True, help_text='Third card eyebrow label, e.g. COVERAGE', max_length=50),
        ),
        migrations.AddField(
            model_name='officessection',
            name='office1_description',
            field=models.TextField(blank=True, help_text='e.g. Company registration, commercial agreements, client relationships and account management for the region.'),
        ),
        migrations.AddField(
            model_name='officessection',
            name='office2_description',
            field=models.TextField(blank=True, help_text='e.g. The technical team — NOC and service desk engineers, automation developers, and back-office process staff.'),
        ),
    ]
