# Generated by Django 5.2.17 on 2026-09-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_officessection_banner_badge1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officessection',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Third card background image', null=True, upload_to='offices/'),
        ),
    ]
