# Generated by Django 5.2.17 on 2026-09-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_officessection_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqsection',
            name='quote_attribution',
            field=models.CharField(blank=True, help_text='e.g. TrueTech', max_length=100),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='copyright_text',
            field=models.CharField(blank=True, help_text='e.g. © 2026 TrueTech. All rights reserved.', max_length=150),
        ),
        migrations.AlterField(
            model_name='siteheader',
            name='brand_name',
            field=models.CharField(default='TrueTech', max_length=100),
        ),
    ]
