# Generated by Django 5.2.17 on 2026-09-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_faqsection_quote_attribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='footersection',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
